export const signUpActionTypes = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}

export const userDetailActionTypes = {
    SET_USER: 'SET_USER'
}

export const loginActionTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE'
}

export const userActionTypes = {
    USER_REQUEST: 'USER_REQUEST',
    USER_SUCCESS: 'USER_SUCCESS',
    USER_FAILURE: 'USER_FAILURE'
}

export const hotTracksActions = {
    HOT_TRACK_REQUEST: 'HOT_TRACK_REQUEST',
    HOT_TRACK_SUCCESS: 'HOT_TRACK_SUCCESS',
    HOT_TRACK_FAILURE: 'HOT_TRACK_FAILURE'
}

export const playbarActionTypes = {
    PLAY: 'PLAY',
    LOOP: 'LOOP',
    PAUSE: 'PAUSE',
    START_TIME: 'START_TIME',
    DURATION: 'DURATION',
    SHOW_TIME: 'SHOW_TIME',
    ARTIST_IMAGE: 'ARTIST_IMAGE',
    ARTIST_NAME: 'ARTIST_NAME',
    ARTIST_TRACK: 'ARTIST_TRACK',
    IS_TRACK_SELECTED: 'IS_TRACK_SELECTED',
    IS_CLOSED: 'IS_CLOSED'
}
